---
name: make-changelog

on:
  release:
    types: [published]

jobs:
  changelog:
    steps:
      - name: Release Changelog Builder
        uses: mikepenz/release-changelog-builder-action@v3.4.0
        with:
          tag: ${{ github.event.release.tag_name }}