---
name: Create Release
concurrency:
  group: create-release
  cancel-in-progress: false

on:
  workflow_dispatch:
    ref: master
    inputs:
      number:
        description: |
          The suffix that we expect to be present for the containers.
        type: string
        required: true
jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "notes" > gh release create ${{ inputs.number }} -F -