---
# The actual deployment.
#  I made a dummy deploy step to abstract away complexity that
#  we don't need for an example workflow.
name: Maether-Deploy
concurrency:
  group: deploy-production
  cancel-in-progress: false

on:
  push:
    branches:
      - main

jobs:
  geilerjob:
    uses: ./.github/workflows/deploy-production.yaml
    with:
      container_suffix: foobar
