---
# The actual deployment.
#  I made a dummy deploy step to abstract away complexity that
#  we don't need for an example workflow.
name: Maether-Deploy
concurrency:
  group: deploy-production
  cancel-in-progress: false

on:
  push:
    branches:
      - main

jobs:
  geilerjob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/deploy-production.yaml