name: Split SDK
on: [push]
jobs:
  split_sdk:
    runs-on: ubuntu-latest
    name: Split SDK
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: 'false'
      - uses: frankdejonge/use-github-token@1.0.2
        with:
          authentication: 'dsentker24:${{ secrets.DSENTKER_GH_TOKEN }}'
          user_name: 'Some Name'
          user_email: 'some.name@example.com'
      - name: Cache splitsh-lite
        id: splitsh-cache
        uses: actions/cache@v3
        with:
          path: './bin/splitsh'
          key: '${{ runner.os }}-splitsh-d-101'
      - name: use-subsplit-publish
        uses: frankdejonge/use-subsplit-publish@1.0.0-beta.6
        with:
          source-branch: 'main'
          config-path: './subsplit.json'
          splitsh-path: './bin/splitsh-lite'
          splitsh-version: 'v1.0.1'